"""esquema inicial

Revision ID: 45a028987ce3
Revises: 
Create Date: 2026-10-05 15:07:22.520097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a028987ce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('criticidad', sa.String(length=10), nullable=False),
    sa.Column('propietario', sa.String(length=120), nullable=False),
    sa.Column('tecnologia', sa.String(length=60), nullable=True),
    sa.CheckConstraint("criticidad IN ('alta', 'media', 'baja')", name='ck_criticidad_dominio'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('evento_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('entidad', sa.String(length=60), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('ocurrido_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_auditoria_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_auditoria_ocurrido_en'), ['ocurrido_en'], unique=False)

    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=False),
    sa.Column('origen_archivo', sa.String(length=255), nullable=True),
    sa.Column('hash_archivo', sa.String(length=64), nullable=True),
    sa.Column('filas_leidas', sa.Integer(), nullable=False),
    sa.Column('filas_descartadas', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('puesto', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=80), nullable=True),
    sa.Column('jefe_legajo', sa.String(length=32), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('ultimo_acceso', sa.Date(), nullable=True),
    sa.CheckConstraint("estado IN ('activo', 'inactivo', 'baja')", name='ck_estado_dominio'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legajo')
    )
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aplicacion_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('nivel', sa.String(length=15), nullable=False),
    sa.Column('peso_riesgo', sa.Integer(), nullable=False),
    sa.CheckConstraint("nivel IN ('lectura', 'escritura', 'administracion')", name='ck_nivel_dominio'),
    sa.CheckConstraint('peso_riesgo BETWEEN 1 AND 10', name='ck_permiso_peso'),
    sa.ForeignKeyConstraint(['aplicacion_id'], ['aplicacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aplicacion_id', 'codigo', name='uq_permiso_app_codigo')
    )
    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permiso_aplicacion_id'), ['aplicacion_id'], unique=False)

    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aplicacion_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('puesto_objetivo', sa.String(length=120), nullable=True),
    sa.Column('area_objetivo', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['aplicacion_id'], ['aplicacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aplicacion_id', 'codigo', name='uq_rol_app_codigo')
    )
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rol_aplicacion_id'), ['aplicacion_id'], unique=False)

    op.create_table('solicitud_alta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('puesto_solicitado', sa.String(length=120), nullable=False),
    sa.Column('area_solicitada', sa.String(length=120), nullable=False),
    sa.Column('permisos_propuestos', sa.JSON(), nullable=False),
    sa.Column('conflictos_detectados', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('solicitada_por', sa.String(length=120), nullable=True),
    sa.Column('resuelta_por', sa.String(length=120), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resuelta_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'aprobada', 'rechazada')", name='ck_estado_dominio'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitud_alta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitud_alta_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('asignacion_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('origen', sa.String(length=15), nullable=False),
    sa.Column('otorgado_por', sa.String(length=120), nullable=True),
    sa.Column('fecha_otorgamiento', sa.Date(), nullable=False),
    sa.Column('fecha_revision', sa.Date(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(origen <> 'rbac_rol') OR (rol_id IS NOT NULL)", name='ck_asignacion_origen_rol'),
    sa.CheckConstraint("origen IN ('rbac_rol', 'abac_atributo', 'directa')", name='ck_origen_dominio'),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'permiso_id', name='uq_asignacion_usuario_permiso')
    )
    with op.batch_alter_table('asignacion_acceso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asignacion_acceso_permiso_id'), ['permiso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asignacion_acceso_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('politica_abac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('condicion', sa.JSON(), nullable=False),
    sa.Column('efecto', sa.String(length=10), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.CheckConstraint("efecto IN ('permitir', 'negar')", name='ck_abac_efecto'),
    sa.CheckConstraint('prioridad BETWEEN 1 AND 100', name='ck_abac_prioridad'),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('politica_abac', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_politica_abac_permiso_id'), ['permiso_id'], unique=False)

    op.create_table('regla_sod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('permiso_a_id', sa.Integer(), nullable=False),
    sa.Column('permiso_b_id', sa.Integer(), nullable=False),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('fundamento', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.CheckConstraint("severidad IN ('critica', 'alta', 'media', 'baja')", name='ck_severidad_dominio'),
    sa.CheckConstraint('permiso_a_id <> permiso_b_id', name='ck_sod_distintos'),
    sa.ForeignKeyConstraint(['permiso_a_id'], ['permiso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permiso_b_id'], ['permiso.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('permiso_a_id', 'permiso_b_id', name='uq_sod_par')
    )
    op.create_table('rol_permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'permiso_id', name='uq_rol_permiso')
    )
    with op.batch_alter_table('rol_permiso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rol_permiso_permiso_id'), ['permiso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rol_permiso_rol_id'), ['rol_id'], unique=False)

    op.create_table('hallazgo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('permiso_id', sa.Integer(), nullable=True),
    sa.Column('regla_sod_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('puntaje', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('evidencia', sa.JSON(), nullable=False),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('detectado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("categoria IN ('cuenta_dormida', 'cuenta_huerfana', 'sobre_privilegio', 'conflicto_sod', 'privilege_creep')", name='ck_categoria_dominio'),
    sa.CheckConstraint("severidad IN ('critica', 'alta', 'media', 'baja')", name='ck_severidad_dominio'),
    sa.CheckConstraint('puntaje >= 0', name='ck_hallazgo_puntaje'),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['regla_sod_id'], ['regla_sod.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hallazgo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hallazgo_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_hallazgo_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hallazgo_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('script_generado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hallazgo_id', sa.Integer(), nullable=True),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('proveedor', sa.String(length=30), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('lenguaje', sa.String(length=30), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('estado_validacion', sa.String(length=10), nullable=False),
    sa.Column('controles', sa.JSON(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('aprobado_por', sa.String(length=120), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado_validacion IN ('pendiente', 'valido', 'rechazado')", name='ck_estado_validacion_dominio'),
    sa.CheckConstraint('(aprobado_por IS NULL) = (aprobado_en IS NULL)', name='ck_script_aprobacion_completa'),
    sa.CheckConstraint('(hallazgo_id IS NOT NULL) OR (solicitud_id IS NOT NULL)', name='ck_script_tiene_origen'),
    sa.ForeignKeyConstraint(['hallazgo_id'], ['hallazgo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_alta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('script_generado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_generado_hallazgo_id'), ['hallazgo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_script_generado_solicitud_id'), ['solicitud_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_generado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_script_generado_solicitud_id'))
        batch_op.drop_index(batch_op.f('ix_script_generado_hallazgo_id'))

    op.drop_table('script_generado')
    with op.batch_alter_table('hallazgo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hallazgo_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_hallazgo_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_hallazgo_categoria'))

    op.drop_table('hallazgo')
    with op.batch_alter_table('rol_permiso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rol_permiso_rol_id'))
        batch_op.drop_index(batch_op.f('ix_rol_permiso_permiso_id'))

    op.drop_table('rol_permiso')
    op.drop_table('regla_sod')
    with op.batch_alter_table('politica_abac', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_politica_abac_permiso_id'))

    op.drop_table('politica_abac')
    with op.batch_alter_table('asignacion_acceso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asignacion_acceso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_asignacion_acceso_permiso_id'))

    op.drop_table('asignacion_acceso')
    with op.batch_alter_table('solicitud_alta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitud_alta_usuario_id'))

    op.drop_table('solicitud_alta')
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rol_aplicacion_id'))

    op.drop_table('rol')
    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permiso_aplicacion_id'))

    op.drop_table('permiso')
    op.drop_table('usuario')
    op.drop_table('snapshot')
    with op.batch_alter_table('evento_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_auditoria_ocurrido_en'))
        batch_op.drop_index(batch_op.f('ix_evento_auditoria_accion'))

    op.drop_table('evento_auditoria')
    op.drop_table('aplicacion')
    # ### end Alembic commands ###
